"""Contract tests for EP-Governance XID format.

These tests validate the XID format contract:
- 20-char lowercase base32hex string
- Characters: 0-9, a-v
- Generated by a pure Python implementation (no broken PyPI xid package)

References: v1.1 section 14, directive section 6
"""

from __future__ import annotations

import re
import pytest


# XID format: 20-char lowercase base32hex
# base32hex alphabet: 0123456789abcdefghijklmnopqrstuv
XID_PATTERN = re.compile(r"^[0-9a-v]{20}$")
XID_LENGTH = 20
XID_ALPHABET = set("0123456789abcdefghijklmnopqrstuv")


class TestXIDFormat:
    """XID format contract tests."""

    @pytest.mark.parametrize(
        "test_xid",
        [
            "cjvbbvh6qgtnoiaaa001",
            "00000000000000000000",
            "vvvvvvvvvvvvvvvvvvvv",
            "cjvbbvh6qgtnoiaaaabc",
        ],
    )
    def test_valid_xid_matches_pattern(self, test_xid: str):
        assert XID_PATTERN.match(test_xid) is not None

    @pytest.mark.parametrize(
        "invalid_xid",
        [
            "cjvbbvh6qgtnoiaaa00",  # too short (18 chars)
            "cjvbbvh6qgtnoiaaa0011",  # too long (22 chars)
            "cjvbbvh6qgtnoiaaa00w",  # 'w' not in base32hex
            "Cjvbbvh6qgtnoiaaa001",  # uppercase not allowed
            "cjvbbvh6qgtnoiaaa00-",  # dash not in alphabet
            "",  # empty
        ],
    )
    def test_invalid_xid_rejected(self, invalid_xid: str):
        assert XID_PATTERN.match(invalid_xid) is None

    def test_xid_length_is_20(self):
        assert XID_LENGTH == 20

    def test_xid_alphabet_is_base32hex(self):
        """XID MUST use the base32hex alphabet: 0-9 and a-v (32 characters)."""
        assert len(XID_ALPHABET) == 32
        assert XID_ALPHABET == set("0123456789abcdefghijklmnopqrstuv")

    def test_xid_alphabet_excludes_wxyz(self):
        """base32hex stops at 'v', not 'z'."""
        assert "w" not in XID_ALPHABET
        assert "x" not in XID_ALPHABET
        assert "y" not in XID_ALPHABET
        assert "z" not in XID_ALPHABET

    def test_xid_alphabet_excludes_uppercase(self):
        assert "A" not in XID_ALPHABET
        assert "Z" not in XID_ALPHABET

    def test_xid_is_time_sortable(self):
        """XID SHOULD be lexicographically sortable (timestamp is first 4 bytes)."""
        # The first characters encode the timestamp, so lexicographic order
        # approximates chronological order.
        xid1 = "cjvbbvh6qgtnoiaaa001"
        xid2 = "cjvbbvh6qgtnoiaaa002"
        assert xid1 < xid2

    def test_xid_is_probabilistically_unique(self):
        """XIDs are probabilistically unique, not guaranteed.
        Collision retry MUST be supported (up to 3 attempts)."""
        MAX_COLLISION_RETRIES = 3
        assert MAX_COLLISION_RETRIES == 3

    def test_fork_safety(self):
        """On process fork, the child MUST re-seed the counter with a random value
        to avoid generating the same XIDs as the parent."""
        pass

    def test_clock_rollback_handling(self):
        """If current time < last-used timestamp, the system MUST use last-used + 1
        to maintain monotonicity."""
        pass

    def test_database_stores_xids_as_text(self):
        """XIDs MUST be stored as TEXT in the database. No server-side ID generation."""
        pass
