"""EP-Governance immutable audit writer and chain verifier.

Implements v1.1.1 §4–5:
  - Only the EP service writes audit events (actor separation).
  - Per-lattice audit heads with row locking serialise concurrent insertions.
  - Full canonical envelope hashing (SHA-256 of canonical JSON).
  - Append-only: no UPDATE or DELETE on ep_events.
  - Verification recomputes every hash and checks the previous_hash linkage.

The hash chain uses SHA-256 of the canonical JSON of the full event envelope:
    {sequence, event_id, event_type, event_data, principal_id, created_at, previous_hash}

Genesis hash (first event's previous_hash): '0' * 64
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from datetime import UTC, datetime
from typing import TYPE_CHECKING, Any

from sqlalchemy import text

from .canonical import canonical_json
from .db.transactions import transaction
from .errors import AuditWriteError
from .xid import XID

if TYPE_CHECKING:
    from sqlalchemy.engine import Connection

__all__ = [
    "GENESIS_HASH",
    "AuditEvent",
    "AuditWriter",
    "AuditVerifier",
]

# The initial previous_hash for the first event in any lattice chain.
GENESIS_HASH = "0" * 64


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------


@dataclass
class AuditEvent:
    """An immutable audit event record.

    Attributes:
        id: XID of this event (generated by the EP service).
        lattice_id: XID of the lattice this event belongs to.
        sequence: Monotonically increasing sequence within the lattice.
        event_type: Event type string (see audit-format.md §2.1).
        event_data: Canonical event payload (type-specific dict).
        previous_hash: event_hash of the preceding event, or GENESIS_HASH.
        event_hash: SHA-256 of canonical JSON of the full envelope.
        actor_principal_id: The agent or human responsible for the operation.
        authenticated_caller_id: The principal that authenticated to EP.
        event_writer_id: Always the EP service principal (trusted writer).
        created_at: ISO 8601 UTC timestamp with microseconds, Z suffix.
    """

    id: str
    lattice_id: str
    sequence: int
    event_type: str
    event_data: dict[str, Any]
    previous_hash: str
    event_hash: str
    actor_principal_id: str
    authenticated_caller_id: str
    event_writer_id: str
    created_at: str

    def to_envelope(self) -> dict[str, Any]:
        """Return the canonical envelope dict used for hash computation.

        High fix 8: the envelope must include ALL immutable identity fields
        to prevent tampering with lattice_id, authenticated_caller_id, or
        event_writer_id without breaking the hash chain.
        """
        return {
            "sequence": self.sequence,
            "event_id": self.id,
            "lattice_id": self.lattice_id,
            "event_type": self.event_type,
            "event_data": self.event_data,
            "actor_principal_id": self.actor_principal_id,
            "authenticated_caller_id": self.authenticated_caller_id,
            "event_writer_id": self.event_writer_id,
            "created_at": self.created_at,
            "previous_hash": self.previous_hash,
        }

    def recompute_hash(self) -> str:
        """Recompute the SHA-256 of the canonical JSON of the envelope."""
        return hashlib.sha256(canonical_json(self.to_envelope()).encode("utf-8")).hexdigest()


# ---------------------------------------------------------------------------
# AuditWriter — only called by the trusted EP service
# ---------------------------------------------------------------------------


class AuditWriter:
    """Writes immutable audit events with per-lattice hash chaining.

    Only the EP service instantiates this class.  The ``ep_service_principal_id``
    is the XID of the EP service principal and is stored as ``event_writer_id``
    on every event.

    All writes are serialised per lattice via row-level locking on
    ``ep_audit_heads`` (``SELECT ... FOR UPDATE`` on PostgreSQL,
    ``BEGIN IMMEDIATE`` on SQLite).
    """

    def __init__(self, conn: Connection, ep_service_principal_id: str) -> None:
        self.conn = conn
        self.ep_service_principal_id = ep_service_principal_id

    def write_event(
        self,
        lattice_id: str,
        event_type: str,
        event_data: dict[str, Any],
        actor_principal_id: str,
        authenticated_caller_id: str,
    ) -> AuditEvent:
        """Write a single audit event atomically (standalone).

        This is a backward-compatible wrapper that owns its own transaction.
        Callers that already hold a transaction (e.g. BranchCommitter.commit)
        MUST call :meth:`write_event_in_transaction` instead to avoid
        committing the outer transaction prematurely.

        If SQLAlchemy has already autobegun a transaction (from prior reads
        on this connection), it is committed first so that a clean explicit
        transaction can be started.

        Returns the fully populated AuditEvent.
        """
        # Commit any pending autobegun transaction so that transaction()
        # can start a clean explicit one.  This is safe because this method
        # explicitly takes ownership of the audit write.
        if self.conn.in_transaction():
            self.conn.commit()
        with transaction(self.conn):
            return self.write_event_in_transaction(
                lattice_id=lattice_id,
                event_type=event_type,
                event_data=event_data,
                actor_principal_id=actor_principal_id,
                authenticated_caller_id=authenticated_caller_id,
            )

    def write_event_in_transaction(
        self,
        lattice_id: str,
        event_type: str,
        event_data: dict[str, Any],
        actor_principal_id: str,
        authenticated_caller_id: str,
    ) -> AuditEvent:
        """Write a single audit event **inside the caller's transaction**.

        Unlike :meth:`write_event`, this method issues **no COMMIT or
        ROLLBACK** — the caller owns the transaction and is responsible for
        committing or rolling back.  This prevents the audit writer from
        stealing transaction ownership from callers such as
        :class:`BranchCommitter` that wrap the audit write in their own
        transaction.

        Steps (all within the caller's transaction):
          1. Lock the ep_audit_heads row for this lattice
             (``SELECT … FOR UPDATE`` on PostgreSQL; on SQLite the caller
             is expected to have begun a write transaction such as
             ``BEGIN IMMEDIATE`` — this method does **not** issue
             ``BEGIN IMMEDIATE`` itself).
          2. Read last_sequence and last_hash.
          3. Generate event_id (XID), next_sequence, created_at (UTC).
          4. Build the canonical envelope and compute event_hash (SHA-256).
          5. INSERT into ep_events (append-only).
          6. UPDATE ep_audit_heads.
          7. Return the fully populated AuditEvent.

        Returns the fully populated AuditEvent.
        """
        conn = self.conn
        dialect = conn.dialect.name

        # 1. Lock the audit head and read current state.
        #    No explicit BEGIN/BEGIN IMMEDIATE here — the caller owns the
        #    transaction.  On SQLite the caller's write transaction already
        #    holds the write lock; on PostgreSQL we use SELECT … FOR UPDATE.
        if dialect == "sqlite":
            # SQLite: the caller's write transaction (e.g. BEGIN IMMEDIATE)
            # already holds a write lock; no FOR UPDATE needed.
            result = conn.execute(
                text(
                    "SELECT last_sequence, last_hash "
                    "FROM ep_audit_heads WHERE lattice_id = :lattice_id"
                ),
                {"lattice_id": lattice_id},
            )
        else:
            # PostgreSQL: row-level lock.
            result = conn.execute(
                text(
                    "SELECT last_sequence, last_hash "
                    "FROM ep_audit_heads WHERE lattice_id = :lattice_id "
                    "FOR UPDATE"
                ),
                {"lattice_id": lattice_id},
            )
        row = result.fetchone()
        if row is None:
            raise AuditWriteError(
                f"No audit head found for lattice '{lattice_id}'. "
                "Ensure the audit head was initialised when the lattice was created."
            )

        last_sequence: int = row[0] if row[0] is not None else 0
        last_hash: str = row[1] if row[1] is not None else GENESIS_HASH

        # 2. Generate event metadata (trusted EP service only)
        event_id = str(XID.new())
        next_sequence = last_sequence + 1
        created_at = _utc_now_iso()

        # 3. Build canonical envelope and compute hash.
        #    The envelope must include ALL immutable identity fields
        #    (lattice_id, authenticated_caller_id, event_writer_id) to
        #    prevent tampering without breaking the hash chain.
        envelope: dict[str, Any] = {
            "sequence": next_sequence,
            "event_id": event_id,
            "lattice_id": lattice_id,
            "event_type": event_type,
            "event_data": event_data,
            "actor_principal_id": actor_principal_id,
            "authenticated_caller_id": authenticated_caller_id,
            "event_writer_id": self.ep_service_principal_id,
            "created_at": created_at,
            "previous_hash": last_hash,
        }
        event_hash = hashlib.sha256(canonical_json(envelope).encode("utf-8")).hexdigest()

        # 4. INSERT into ep_events (append-only)
        conn.execute(
            text(
                "INSERT INTO ep_events "
                "(id, lattice_id, sequence, event_type, event_data, "
                " previous_hash, event_hash, actor_principal_id, "
                " authenticated_caller_id, event_writer_id, created_at) "
                "VALUES "
                "(:id, :lattice_id, :sequence, :event_type, :event_data, "
                " :previous_hash, :event_hash, :actor_principal_id, "
                " :authenticated_caller_id, :event_writer_id, :created_at)"
            ),
            {
                "id": event_id,
                "lattice_id": lattice_id,
                "sequence": next_sequence,
                "event_type": event_type,
                "event_data": _dump_json(event_data),
                "previous_hash": last_hash,
                "event_hash": event_hash,
                "actor_principal_id": actor_principal_id,
                "authenticated_caller_id": authenticated_caller_id,
                "event_writer_id": self.ep_service_principal_id,
                "created_at": created_at,
            },
        )

        # 5. UPDATE ep_audit_heads
        conn.execute(
            text(
                "UPDATE ep_audit_heads "
                "SET last_sequence = :last_sequence, last_hash = :last_hash "
                "WHERE lattice_id = :lattice_id"
            ),
            {
                "last_sequence": next_sequence,
                "last_hash": event_hash,
                "lattice_id": lattice_id,
            },
        )

        # 6. Return the fully populated AuditEvent.
        #    No COMMIT/ROLLBACK — the caller owns the transaction.
        return AuditEvent(
            id=event_id,
            lattice_id=lattice_id,
            sequence=next_sequence,
            event_type=event_type,
            event_data=event_data,
            previous_hash=last_hash,
            event_hash=event_hash,
            actor_principal_id=actor_principal_id,
            authenticated_caller_id=authenticated_caller_id,
            event_writer_id=self.ep_service_principal_id,
            created_at=created_at,
        )


# ---------------------------------------------------------------------------
# AuditVerifier — recomputes the chain
# ---------------------------------------------------------------------------


class AuditVerifier:
    """Verifies audit chain integrity by recomputing every event hash.

    For each lattice:
      - Read all events ordered by sequence.
      - Recompute the canonical envelope and SHA-256 hash for each event.
      - Compare to the stored event_hash.
      - Check that previous_hash matches the preceding event's event_hash
        (or GENESIS_HASH for the first event).
    """

    def __init__(self, conn: Connection) -> None:
        self.conn = conn

    def verify(self, lattice_id: str) -> bool:
        """Verify the audit chain for a single lattice.

        Returns True if every event's recomputed hash matches its stored
        event_hash and the previous_hash linkage is correct.
        Returns False on the first mismatch.
        """
        conn = self.conn
        result = conn.execute(
            text(
                "SELECT id, sequence, event_type, event_data, "
                "       previous_hash, event_hash, actor_principal_id, "
                "       authenticated_caller_id, event_writer_id, created_at "
                "FROM ep_events "
                "WHERE lattice_id = :lattice_id "
                "ORDER BY sequence"
            ),
            {"lattice_id": lattice_id},
        )
        rows = result.fetchall()
        if not rows:
            # No events — nothing to verify.
            return True

        expected_previous_hash = GENESIS_HASH

        for row in rows:
            event = AuditEvent(
                id=row[0],
                lattice_id=lattice_id,
                sequence=row[1],
                event_type=row[2],
                event_data=_load_json(row[3]),
                previous_hash=row[4],
                event_hash=row[5],
                actor_principal_id=row[6],
                authenticated_caller_id=row[7],
                event_writer_id=row[8],
                created_at=row[9],
            )

            # Recompute hash from the canonical envelope
            recomputed = event.recompute_hash()
            if recomputed != event.event_hash:
                return False

            # Check previous_hash linkage
            if event.previous_hash != expected_previous_hash:
                return False

            expected_previous_hash = event.event_hash

        return True

    def verify_all(self) -> dict[str, bool]:
        """Verify the audit chains for all lattices.

        Returns a mapping of lattice_id -> bool (True = chain valid).
        """
        conn = self.conn
        result = conn.execute(text("SELECT DISTINCT lattice_id FROM ep_events ORDER BY lattice_id"))
        lattice_ids = [row[0] for row in result.fetchall()]

        return {lid: self.verify(lid) for lid in lattice_ids}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _utc_now_iso() -> str:
    """Return the current UTC timestamp as ISO 8601 with microseconds and Z suffix.

    Format: YYYY-MM-DDTHH:MM:SS.ffffffZ
    """
    dt = datetime.now(UTC)
    return dt.strftime("%Y-%m-%dT%H:%M:%S.%f") + "Z"


def _dump_json(obj: dict[str, Any]) -> str:
    """Serialise event_data to a JSON string for storage.

    Uses canonical_json so the stored representation is deterministic.
    """
    return canonical_json(obj)


def _load_json(s: str | bytes | None) -> dict[str, Any]:
    """Parse event_data from a stored JSON string back to a dict."""
    if s is None:
        return {}
    if isinstance(s, (bytes, bytearray)):
        s = s.decode("utf-8")
    import json

    return json.loads(s)
